<a href="https://colab.research.google.com/github/pedroagreda/TMD/blob/master/ApuntesIntro2Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
#numpy -> arrays multidimensionales y matrices

# 2. Numpy exercises

2.1. Create numpy arrays

In [3]:
x=[5, 4, 3, 4]
print(type(x[0]))

<class 'int'>


In [0]:
#Enunciado: Crea una lista de tipo float con los mismos elementos que x
#x_f = []
#for element in x:
  #<FILL IN>
  
#print(x_f)
#print(type(x_f[0]))




In [4]:
#Solución
x_f = []
for element in x:
  #<FILL IN> Añadir elementos a una lista -> .append de tipo float siendo element cada posicion recorrida en el for en la lista x
  x_f.append(float(element))
  
print(x_f)
print(type(x_f[0]))

[5.0, 4.0, 3.0, 4.0]
<class 'float'>


Numpy is a python library that lets you work with **VECTORES DE DATOS Y MATRICES** (we will call them numpy arrays) and directly apply operations over these arrays without the need to operate element by element.

Numpy arrays can be defined directly using methods such as **np.arange(), np.ones(), np.zeros(), np.eye()**, as well as random number generators. 

Alternatively, you can easily generate them from python lists (or lists of lists) containing elements of a numerical type by using np.array(my_list).

You can easily check the shape of any numpy array with the property .shape.


In [5]:
# Numpy arrays can be created from numeric lists or using different numpy methods
y = np.arange(8) + 1
x = np.array(x_f)
z = np.array([[1, 2], [2, 1]])

# The arange() function generates vectors of equally spaced numbers. We can 
# specify start and stop positions as well as the step length (the steps don't 
# need to be integers!):
print('A vector that goes from 2 to 8 in steps of 2: ', np.arange(2, 9, 2))

# Numpy also has a linspace() function that works exactly like its Matlab 
# counterpart:
print('\nA vector of length 5 that spans from 0 to 1 in constant increments:\n', 
      np.linspace(0, 1, 5))

# Check the different data types involved
print('\nThe type of variable x_f is ', type(x_f))
print('The type of variable x is ', type(x))

# Print the shapes of the numpy arrays
print('\nThe variable x has shape ', x.shape)
print('The variable y has shape ', y.shape)
print('The variable z has shape ', z.shape)



#Note: Compare the shape of x and y with the shape of z and note the difference between 1-D and N-D numpy arrays (ndarrays). 
#We will later review this issue in detail.

A vector that goes from 2 to 8 in steps of 2:  [2 4 6 8]

A vector of length 5 that spans from 0 to 1 in constant increments:
 [0.   0.25 0.5  0.75 1.  ]

The type of variable x_f is  <class 'list'>
The type of variable x is  <class 'numpy.ndarray'>

The variable x has shape  (4,)
The variable y has shape  (8,)
The variable z has shape  (2, 2)


We can also convert a numpy array or matrix into a python list with the method **np.tolist().**



In [6]:
my_array = np.arange(9).reshape((3, 3))
print(my_array)
print('the type is: ', type(my_array))

# Convert my_array to list

my_array_list =  my_array.tolist()
print('\n', my_array_list)
print('the type is: ',type(my_array_list))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
the type is:  <class 'numpy.ndarray'>

 [[0, 1, 2], [3, 4, 5], [6, 7, 8]]
the type is:  <class 'list'>


In [7]:
#Ejercicios
# 1. Define a new 3x2 array named my_array with [1, 2, 3] in the first row and 
# [4, 5, 6] in the second. Check the dimension of the array.
#my_array = <FILL IN> ----- 

my_array =np.array([[1,2,3],[4,5,6]])
print(my_array)
print('Its shape is: ', np.shape(my_array))

#2. Define a new 3x4 array named my_zeros with all its elements to zero
#my_zeros = <FILL IN>

my_zeros = np.zeros((3,4))  #siempre entre parentesis tras np.x; si das dimensiones ()
                                                                # si das directamente los elementos [[1,2,3]]
print('A 3x4 vector of zeros:') 
print(my_zeros)

#3. Define a new 4x2 array named my_ones with all its elements to one
#my_ones = <FILL IN>
my_ones= np.ones((4,2))
print('A 4x2 vector of ones:') 
print(my_ones)

#4. Modify the dimensions of my_ones to a 2x4 array using command np.reshape()
#my_ones2 = <FILL IN>

my_ones2 = my_ones.reshape((2,4))
print('A 2x4 vector of ones:') 
print(my_ones2)

#5. Define a new 4x4 identity array named my_eye 
#my_eye = <FILL IN>

my_eye = np.identity(4).reshape((4,4)) #np.identity -> matriz de identidad
my_eye2=np.eye((4))
print('A 4x4 identity vector:') 
print(my_eye)
print(my_eye2)

[[1 2 3]
 [4 5 6]]
Its shape is:  (2, 3)
A 3x4 vector of zeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
A 4x2 vector of ones:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
A 2x4 vector of ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
A 4x4 identity vector:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# 2.2 Numpy operations

In [8]:
#Sumar y Restar
x1 = np.arange(9).reshape((3, 3))
x2 = np.ones((3, 3))
result= x1 + x2
print('x1:\n', x1, '\n\nx2:\n', x2)
print('\nAddition of x1 and x2 using the + operator:\n', result)

x1:
 [[0 1 2]
 [3 4 5]
 [6 7 8]] 

x2:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Addition of x1 and x2 using the + operator:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [9]:
#Añadir o restar 2 arrays de forma built-in
x1 = np.arange(9).reshape((3, 3))
x2 = np.ones((3, 3))
result = np.add(x1, x2)    #O en el caso de restar, np.subtract(x1,x2)
print('x1:\n', x1, '\n\nx2:\n', x2)
print('\nAddition of x1 and x2 using built-in functions:\n', result)


x1:
 [[0 1 2]
 [3 4 5]
 [6 7 8]] 

x2:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Addition of x1 and x2 using built-in functions:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [10]:
# We can add or subtract row and column vectors:
row_vect = np.ones((1, 3))
col_vect = np.ones((3, 1))
result = np.add(x1, row_vect)
print('x1:\n', x1, '\n\nrow_vect:\n', row_vect, '\n\ncol_vect:\n', col_vect)
print('\nAddition of a row vector:\n', result)
result = np.add(x1, col_vect)
print('\nAddition of a column vector:\n', result)

x1:
 [[0 1 2]
 [3 4 5]
 [6 7 8]] 

row_vect:
 [[1. 1. 1.]] 

col_vect:
 [[1.]
 [1.]
 [1.]]

Addition of a row vector:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

Addition of a column vector:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [11]:
#El operando "*" no te hace multiplicación de matrices, element-wise multiplication

# We can perform element-wise multiplication by using the * operator:
x1 = np.arange(9).reshape((3, 3))
x2 = np.ones((3, 3)) * 2 # a 3x3 array with 2s in every cell
result = x1 * x2
print('x1:\n', x1, '\n\nx2:\n', x2)
print('\nElement-wise multiplication of x1 and x2 using the * operator:\n', result)

# or by using the built-in numpy function:
result = np.multiply(x1, x2)
print('\nElement-wise multiplication of x1 and x2 using built-in functions:\n', result)

x1:
 [[0 1 2]
 [3 4 5]
 [6 7 8]] 

x2:
 [[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]

Element-wise multiplication of x1 and x2 using the * operator:
 [[ 0.  2.  4.]
 [ 6.  8. 10.]
 [12. 14. 16.]]

Element-wise multiplication of x1 and x2 using built-in functions:
 [[ 0.  2.  4.]
 [ 6.  8. 10.]
 [12. 14. 16.]]


In [12]:
# We can perform matrix multiplication:
x1 = np.arange(9).reshape((3, 3))
x2 = np.ones((3, 3)) * 2 # a 3x3 array with 2s in every cell
result = np.matmul(x1, x2) #Multiplicacion de matrices
print('x1:\n', x1, '\n\nx2:\n', x2)
print('\nProduct of x1 and x2:\n', result)

# Or the dot product between vectors:
v1 = np.arange(4)
v2 = np.arange(3, 7)
result = np.dot(v1, v2) #PARA VECTORES y también vale como np.matmul()
print('\nv1:\n', v1, '\n\nv2:\n', v2)
print('\nDot product of v1 and v2:\n', result)

x1:
 [[0 1 2]
 [3 4 5]
 [6 7 8]] 

x2:
 [[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]

Product of x1 and x2:
 [[ 6.  6.  6.]
 [24. 24. 24.]
 [42. 42. 42.]]

v1:
 [0 1 2 3] 

v2:
 [3 4 5 6]

Dot product of v1 and v2:
 32


In [13]:
# Examples of element-wise numerical operations:
x1 = np.arange(9).reshape((3, 3)) + 1
print('x1:\n', x1)
print('\nExponentiation of x1:\n', np.exp(x1))
print('\nLogarithm of x1:\n', np.log(x1))
print('\nSquare root of x1:\n', np.sqrt(x1))

x1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Exponentiation of x1:
 [[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

Logarithm of x1:
 [[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]]

Square root of x1:
 [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [14]:
#Element-wise division between matrices is performed using the ''/'' operator or the divide() built-in function:
# Element-wise division of two matrices:
x1 = np.arange(9).reshape((3, 3)) * 3
x2 = np.ones((3, 3)) * 3
result = np.divide(x1, x2)
result2= x1/x2
print('x2: \n', result2)
print('x1:\n', x1, '\n\nx2:\n', x2)
print('\nElement-wise division of x1 and x2:\n', result)

x2: 
 [[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
x1:
 [[ 0  3  6]
 [ 9 12 15]
 [18 21 24]] 

x2:
 [[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]

Element-wise division of x1 and x2:
 [[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [15]:
#We can use the ''**'' operator or the power() built-in function to raise elements from a matrix to a given power, 
#or to raise elements of one matrix to positionally-corresponding powers in another matrix:
# Performing power operations with the ** operator:
x1 = np.arange(9).reshape((3, 3))
result = x1**2
print('x1:\n', x1)
print('\nRaising all elements in x1 to the power of 2 using the ** operator:\n', result)

result = x1**x1
print('\nRaising all elements in x1 to themselves using the ** operator:\n', result)

# Performing power operations with the power() function:
result = np.power(x1, 2)
print('\nRaising all elements in x1 to the power of 2 using the power() function:\n', result)

result = np.power(x1, x1)
print('\nRaising all elements in x1 to themselves using the power() function:\n', result)

x1:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Raising all elements in x1 to the power of 2 using the ** operator:
 [[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]

Raising all elements in x1 to themselves using the ** operator:
 [[       1        1        4]
 [      27      256     3125]
 [   46656   823543 16777216]]

Raising all elements in x1 to the power of 2 using the power() function:
 [[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]

Raising all elements in x1 to themselves using the power() function:
 [[       1        1        4]
 [      27      256     3125]
 [   46656   823543 16777216]]


In [16]:
#Transponer una matriz np.transpose()
# Three different ways of transposing a matrix:
x1 = np.arange(9).reshape((3, 3))
print('x1:\n', x1)
print('\nTranspose of x1 using the numpy function:\n', np.transpose(x1)) #1
print('\nTranspose of x1 using the ndarray method:\n', x1.transpose()) #2
print('\nTranspose of x1 using the abbreviated form:\n', x1.T)  #3
print('\nOddly enough, the three methods produce the same result!')


x1:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Transpose of x1 using the numpy function:
 [[0 3 6]
 [1 4 7]
 [2 5 8]]

Transpose of x1 using the ndarray method:
 [[0 3 6]
 [1 4 7]
 [2 5 8]]

Transpose of x1 using the abbreviated form:
 [[0 3 6]
 [1 4 7]
 [2 5 8]]

Oddly enough, the three methods produce the same result!


In [0]:
# Complete the following exercises. Print the partial results to visualize them.

# Create a 3x4 array called `y`. It's up to you to decide what it contains.
y = np.arange(12).reshape((3, 4))
#y = <FILL IN>

# Create a column vector of length 3 called `x_col`. 
x_col = np.ones((3, 1)) * 2
#x_col = <FILL IN>

# Multiply the 2-D array `y` by 2
y_by2 = y * 2
#y_by2 = <FILL IN>

# Multiply each of the columns in `y` by the column vector `x_col`
z = x_col * y
#z = <FILL IN>

# Obtain the matrix product of the transpose of x_col and y
x_by_y = x_col.transpose()*y.transpose()
#x_by_y = <FILL IN>

# Compute the sine of a vector that spans from -5 to 5 in increments of 0.5
x = np.arange(-5, 5.5, 0.5)
x_sin = np.sin(x)
#x = <FILL IN>
#x_sin = <FILL IN>

# 2.2. N-D numpy arrays


In [0]:
#ejemplo de array de 1-D y 2-D
array1 = np.array([1,1,1])
print('array1:\n', array1)

array2 = np.ones((3,1))
print('\narray2:\n', array2)

#Modificar la dimensión de un array, flatten(), ravel() and reshape()
x1 = np.arange(9).reshape((3, 3))
print('x1:\n', x1)
print('Its shape is: ', x1.shape)

print('\n Use the method flaten:')
print('x1.flatten(): ', x1.flatten())
print('Its shape is: ', x1.flatten().shape)

print('\n Use the method ravel:')
print('x1.ravel(): ', x1.ravel())
print('Its shape is:', x1.ravel().shape)

print('\n Use the method shape:')
print('x1.reshape(-1): ', x1.reshape(-1))
print('Its shape is: ', x1.reshape(-1).shape)

#Utilizar reshape() tiene que cumplirse que i*j=i'*j'
print('\n A more common use of reshape():')
x1 = np.arange(12).reshape((4, 3))
print('x1:\n', x1)
print('Its shape is: ', x1.shape)

print('\nx1.reshape((2,6)):\n', x1.reshape((2,6)))
print('Its shape is: ', x1.reshape((2,6)).shape)

In [20]:
#Para pasar de array 1-D a 2-D

# Let's start with a 1-D array:
array1 = np.array([1,1,1,])
print('1D array:\n',array1)
print('Its shape is: ', array1.shape)

# Let's turn it into a column vector (2-D array with dimension 1x3):
array2 = array1[:,np.newaxis]
print('\n2D array:\n',array2)
print('Its shape is: ', array2.shape)

# Let's turn it into a row vector (2-D array with dimension 3x1):
array3 = array1[np.newaxis,:]
print('\n2D array:\n',array3)
print('Its shape is: ', array3.shape)

1D array:
 [1 1 1]
Its shape is:  (3,)

2D array:
 [[1]
 [1]
 [1]]
Its shape is:  (3, 1)

2D array:
 [[1 1 1]]
Its shape is:  (1, 3)


In [22]:
#Para quitar dimensiones vacias o inutilizadas ---> np.squeeze()

array1 = np.array([1,1,1,])
array2 = array1[:,np.newaxis]

array1_1D = np.squeeze(array1)
print('1D array:\n',array1_1D)
print('Its shape is: ', array1_1D.shape)

array2_1D = np.squeeze(array2)
print('\n1D array:\n',array2_1D)
print('Its shape is: ', array2_1D.shape)

array3_1D = np.squeeze(array3)
print('\n1D array:\n',array3_1D)
print('Its shape is: ', array3_1D.shape)

1D array:
 [1 1 1]
Its shape is:  (3,)

1D array:
 [1 1 1]
Its shape is:  (3,)

1D array:
 [1 1 1]
Its shape is:  (3,)


In [28]:
#Ejercicios:

# Given the following matrix and vector:
vect = np.arange(3)[:, np.newaxis]
mat = np.arange(9).reshape((3, 3))

# Apply the necessary transformation to vect so that you can perform the matrix
# multiplication np.matmul(vect, mat)
vect = vect.reshape(1,3)

# <FILL IN>
print(np.matmul(vect, mat))

[[0]
 [1]
 [2]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]]
[15 18 21]


# 2.3. Numpy methods that can be carried out along different dimensions